### ISSUE TITLE
How can I use this package with Collection of a Model ?

### ISSUE THREAD

**Issue by rabin-io** [spatie/laravel-view-models#20]
In my index method of the Controller I fetch all users and I like to pass them to the view to allow for replacing some status code with text strings

```php
    public function index()
    {
        $users = Users::all();

        return view('users.index', compact('users')); // <- can't use with ModelView as it expecting A User Model.
    }
```

Should I create a method which get the collection and convert each item to the view model object and pass that to the view ?

**Comment by brendt** [comment]
No, you'd pass the collection to the viewmodel

**Comment by rabin-io** [comment]
Sorry for the noob question, but I get this error when I pass the Collection directly to the ViewModel

    Argument 1 passed to App\ViewModels\RegistrarViewModel::__construct() must be an instance of App\Registrar or null, instance of Illuminate\Database\Eloquent\Collection given


```php
# MyController
    public function index()
    {     
        $registrars = new RegistrarViewModel(Registrar::all());

        return view('registrars.index', compact('registrars'));
    }
```

```php
# My ViewModel
    public function __construct(Registrar $registrar = null)
    {
        $this->registrar = $registrar ?? new Registrar();
    }
```

So should I just expand the constructor to deal with Collection as well ?
somthing like this:

```php
        foreach ($registrars as $key => &$registrar) {
            $registrars[$key] = new RegistrarViewModel($registrar);
        }
```

**Comment by brendt** [comment]
You should change the viewmodel constructor:

```php

**Comment by rabin-io** [comment]
Sorry for bugging , 

But if like to handle both cases (Single and Collection) in the same ViewModel
I should refactor the `__construct` to handle both cases ?, 
and in the case of Collection just loop over the object and convert them one by one ?

**Comment by brendt** [comment]
I'd make two viewmodels.

**Comment by rabin-io** [comment]
OK, 
thank you
