### ISSUE TITLE
using repositories/dependencies? 

### ISSUE THREAD

**Issue by shez1983** [spatie/laravel-view-models#22]
so previously i had code like this in my controller: (simplified, lots more repos)
```
$data = [
            'locations' => $locationRepository->all()
];
```

I am having trouble moving the repo to the view Modal (VM)? 

if i add these dep into VM's __construct then i'll have to manually add them when i call this view modal..

if i add it to the function getLocations() on the VM then i still need to pass in the repo when calling getLocations..  or instantiate a new Repo inside getLocations() 

the last solution looks ok - but was wondering on any suggestions?

at the moment i am trying this:
```        
$viewModel = new AssignmentViewModel($request, $tutorRepository, $studentRepository, $locationRepository);
``` 

```
class AssignmentViewModel extends ViewModel
{
    public ... 

    public function __construct(
        Request $request,
        TutorRepository $tutorRepository,
        StudentRepository $studentRepository,
        LocationRepository $locationRepository
    )
```
and creating all variables in construct instead of having their own functions.. :/ e.g for locations or students etc

**Comment by brendt** [comment]
My suggestion would be to inject them in the constructor, even if it means you'll need to manually pass it in. This keeps the code maintainable in the long run. I wrote about it here: https://stitcher.io/blog/laravel-beyond-crud-08-view-models
