### ISSUE TITLE
Every public method is called on initialization

### ISSUE THREAD

**Issue by sabat24** [spatie/laravel-view-models#26]
Is that correct behaviour that each public method from viewMethod is called when I pass view model to blade template even if I don't use it there?

My controller
```php
$viewModel = new AgendaViewModel($event, $agenda);
return $this->view('periodicity', $viewModel);
```

_periodicity_ is an empty view - there is nothing inside there

AgendaViewModel
```php
public function __construct(Event $event, Agenda $agenda = null)
{
    $this->event = $event;
    $this->agenda = $agenda;
}

public function singleAgenda()
{
        dump('1');
        return [];
}

public function agendas()
{
        dump('2');
        return [];
}
```

When `viewModel` is passed to the `view` each public method is called and I can see two `dumps`. However I didn't use these methods anywhere. 
Is such behaviour a bug or feature?

**Comment by brendt** [comment]
It's a feature, the view model will be parsed in full before being passed to the view.

**Comment by sabat24** [comment]
In my latest project I need to modify your solution a little bit to not call every method during model construction. My use cases were following:

First of all I needed to use my `ViewModel` class in few similar views. All views shared majority of methods, but some methods were unique for some views. I don't want to expose all methods in view B because of some extra DB calls. The only way to achieve that goal was to add an obsolete argument to the method like `listActiveUsers($a=true)`. Because methods with arguments weren't call on create.
To solve that problem I created `$lazyLoad` property. If method's name is on the list, it will be treated like a method with argument. Closure will be created instead of calling method and put result to the public property. 

In second case I had got some simple logic in template. Let's say that I want to display list of inactive or active users depends on some simple condition. What's more for some reason I want to display them in two places.

Main disadvantage of lazy-loaded solution is lack of caching results. In your approach there were only one method call during construction and it's result was assigned to variable. 
I needed a solution which allows me also to cache the result of my lazy-loaded call. As a result I adopted some kind of caching mechanism. Which also allows me to cache methods with arguments, which weren't possible in original approach.

I created a class which extends your `ViewModel` class.

```php
class Core extends ViewModel
{
    protected $lazyLoad = [];

    public function cache($function)
    {
        return function () use ($function) {
            static $cache = [];
            $args = func_get_args();
            $key = serialize($args);
            if (! isset($cache[$key]) && ! array_key_exists($key, $cache)) {
                $cache[$key] = call_user_func_array($function, $args);
            }

            return $cache[$key];
        };
    }

    protected function items(): Collection
    {
        $publicProperties = parent::items();

        $class = new ReflectionClass($this);
        $protectedMethods = collect($class->getMethods(ReflectionMethod::IS_PROTECTED))->reject(function (ReflectionMethod $method) {
            return $this->shouldIgnoreProtected($method->getName());
        })->mapWithKeys(function (ReflectionMethod $method) {
            $function = $this->createVariableFromMethod($method);
            $cached = $this->cache($function);

            return [$method->getName() => $cached];
        });

        return $protectedMethods->merge($publicProperties);
    }

    protected function shouldIgnoreProtected(string $methodName)
    {
        return ! in_array($methodName, $this->lazyLoad);
    }

    protected function createVariableFromMethod(ReflectionMethod $method)
    {
        if (! in_array($method->getName(), $this->lazyLoad) && $method->getNumberOfParameters() === 0) {
            return $this->{$method->getName()}();
        }

        return Closure::fromCallable([$this, $method->getName()]);
    }
```

If I want to not call my method during construction I can add it's name to `$lazyLoad` property
```php
class UserViewModel extends Core {
    protected $lazyLoad = ['listActive', 'listInactive'];
}
```

If the result shouldn't be cached I set my methods to be public ones. If result should be cached I made them protected. 

```php
public function listActive() {
    return true;
}

protected function listInactive() {
    return true;
}
```

I checked your tests and everything passed.
I just wanted to share my solution if someone else also wants something like that.

**Comment by buismaarten** [comment]
Is there a possibility to only execute the methods when calling the method in Blade like `$method()`? I think most ViewModels are used all over the place inside one controller, not every view is using all the defined methods in the ViewModel.

Is there any other solution?

**Comment by sabat24** [comment]
Have you tried my solution? It works for me quite well.

**Comment by buismaarten** [comment]
Some ideas sounds great to me, however your code feels a bit verbose. I think I will create a base class with a modified `createVariableFromMethod()`-method to always use methods like `$method()` in Blade views.

Thanks.

**Comment by sabat24** [comment]
I mentioned above that you can also use some simple workaround in your ViewModel like that:

```public function method($a=true) {}```

Then this method won't be parsed and executed by default as it has got a parameter. In blade you can use it just like that `$method()`

All in all there are no other solutions.
