### ISSUE TITLE
Add make: command

### ISSUE THREAD

**Issue by brendt** [spatie/laravel-view-models#4]

**Comment by freekmurze** [comment]
Much like how `php artisan make:model` works `php artisan make:view-model MyViewModel` should create a new `MyViewModel` class in `app/ViewModels`, `php artisan make:view-model "MyCustomNamespace\MyViewModel` should create a new `MyViewModel` in `app/MyCustomNameSpace/ViewModels`.

**Comment by ijpatricio** [comment]
Hey @freekmurze @brendt 

As it's so similar to generating an Eloquent Model, and is extending `Illuminate\Console\GeneratorCommand`, are tests required?

Are you happy with the stub contents?

**Comment by freekmurze** [comment]
Underway in #5
