### ISSUE TITLE
Nested ViewModel doesn't get created under the ViewModels namespace

### ISSUE THREAD

**Issue by Wulfheart** [spatie/laravel-view-models#42]
When using the command `php artisan make:view-model Game/IndexGamesViewModel` a view model gets create under the namespace `App\Game` instead of `App\ViewModels\Game` as expected (e.g. compare the `make:controller` command).

As per https://github.com/spatie/laravel-view-models/blob/main/tests/ViewModelMakeCommandTest.php it is the desired behaviour but what about synchronizing it to other Laravel behaviours?

I'd be willing to contribute this enhancement.

**Comment by freekmurze** [comment]
We'd accept a PR that fixes this.
