### ISSUE TITLE
Simplify toResponse method on ViewModel

### ISSUE THREAD

**Issue by SamuelNitsche** [spatie/laravel-view-models#9]
Hey, I am not quite sure but I think the `toResponse` method on `ViewModel.php` can be simplified.
The original method looks like this:
```
public function toResponse($request): Response
{
    if ($request->wantsJson()) {
        return new JsonResponse($this->items());
    }
    
    if ($this->view) {
        return response()->view($this->view, $this);
    }
    
    return new JsonResponse($this->items());
}
```

I think you can remove the first if statement so the method looks like this:

```
public function toResponse($request): Response
{
    if ($this->view) {
        return response()->view($this->view, $this);
    }

    return new JsonResponse($this->items());
}
```

**Comment by coderatio** [comment]
I think it's cleaner too.

**Comment by freekmurze** [comment]
Feel free to send a PR, all current tests should pass.

**Comment by sebastiandedeyne** [comment]
I don't think this is correct. Right now you can specify a view for plain requests and fall back to JSON automatically in AJAX requests. The simplified version doesn't handle that case.

If the tests still pass after the suggested change, I think we need another test case (unless I'm overlooking something)

**Comment by SamuelNitsche** [comment]
With the new version all currently available tests pass. I don’t think that this breaks something since the if statement des the same as the Json fallback.

**Comment by freekmurze** [comment]
But if there is a view present in the view model and the request wants json a response we still need to return the json representation. @sebastiandedeyne is right in saying that we need an extra test to cover this scenario.

**Comment by SamuelNitsche** [comment]
Got it. Then the current implementation is perfectly fine. As you said another test would be good.

**Comment by freekmurze** [comment]
I've correct the tests. When removing

```
if ($request->wantsJson()) {
    return new JsonResponse($this->items());
}
```

the tests will now fail.

**Comment by SamuelNitsche** [comment]
Yeah, makes totally sense. Thanks for clarifying.
